name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.23.4

      - run: |
          CGO_ENABLED=0 GOARCH=amd64 go build -o hud-linux-x86_64 main.go
          CGO_ENABLED=0 GOARCH=arm64 go build -o hud-linux-aarch64 main.go

      - uses: softprops/action-gh-release@v1
        with:
          files: hud-*
